[program:tg-bot-manager]
command=/home/w3c_offical/.local/bin/watchmedo auto-restart --directory=. --pattern=*.py --recursive -- /usr/bin/python3 supervisor_manager.py
directory=/home/w3c_offical/projects/ai-workers/tg-bot
autostart=true
autorestart=true
stdout_logfile=/home/w3c_offical/projects/ai-workers/tg-bot/logs/manager.out.log
stderr_logfile=/home/w3c_offical/projects/ai-workers/tg-bot/logs/manager.err.log
user=w3c_offical
environment=PYTHONPATH="/home/w3c_offical/projects/ai-workers/tg-bot"
